runtime: python38
instance_class: F4_1G
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 300
  cpu_utilization:
    target_utilization: 0.8

resources:
  cpu: 2
  memory_gb: 3

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 60
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2